(function(){'use strict';document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();function init(){setupMobileNav();setupQuickNav();setupFaqAccordion();setupScrollAnimations();setupSmoothScroll();setupRatingBars();setupLazyImages();setupProgressBar();setupHeaderScroll()}
function setupMobileNav(){var toggle=document.getElementById('navToggle');var nav=document.getElementById('nav');if(!toggle||!nav)return;var closeNav=function(){toggle.classList.remove('active');nav.classList.remove('active');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Open menu');document.body.style.overflow=''};toggle.addEventListener('click',function(){var isOpen=nav.classList.toggle('active');toggle.classList.toggle('active');toggle.setAttribute('aria-expanded',isOpen?'true':'false');toggle.setAttribute('aria-label',isOpen?'Close menu':'Open menu');document.body.style.overflow=isOpen?'hidden':''});nav.querySelectorAll('.nav-link').forEach(function(link){link.addEventListener('click',closeNav)});document.addEventListener('click',function(e){if(!nav.contains(e.target)&&!toggle.contains(e.target)&&nav.classList.contains('active')){closeNav()}});document.addEventListener('keydown',function(e){if(e.key==='Escape'&&nav.classList.contains('active')){closeNav();toggle.focus()}})}
function setupQuickNav(){var qLinks=document.querySelectorAll('.quick-nav-list a');var navLinks=document.querySelectorAll('.nav-link');var sections=[];qLinks.forEach(function(link){var href=link.getAttribute('href');if(href&&href.startsWith('#')){var section=document.querySelector(href);if(section)sections.push({el:section,link:link})}});if(sections.length===0)return;var ticking=!1;function updateActive(){var scrollPos=window.pageYOffset+160;var current=null;for(var i=sections.length-1;i>=0;i--){if(sections[i].el.offsetTop<=scrollPos){current=sections[i];break}}
qLinks.forEach(function(l){l.classList.remove('active')});navLinks.forEach(function(l){l.classList.remove('active')});if(current){current.link.classList.add('active');var id=current.link.getAttribute('href');navLinks.forEach(function(l){if(l.getAttribute('href')===id)l.classList.add('active');})}
ticking=!1}
window.addEventListener('scroll',function(){if(!ticking){requestAnimationFrame(updateActive);ticking=!0}},{passive:!0})}
function setupFaqAccordion(){var items=document.querySelectorAll('.faq-item');items.forEach(function(item){var question=item.querySelector('.faq-question');if(!question)return;question.addEventListener('click',function(){var isActive=item.classList.contains('active');items.forEach(function(other){var btn=other.querySelector('.faq-question');if(btn)btn.setAttribute('aria-expanded','false');other.classList.remove('active')});if(!isActive){item.classList.add('active');question.setAttribute('aria-expanded','true')}})})}
function setupScrollAnimations(){var els=document.querySelectorAll('[data-animate]');if(els.length===0)return;if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){els.forEach(function(el){el.classList.add('animated')});return}
if('IntersectionObserver' in window){var observer=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){entry.target.classList.add('animated');observer.unobserve(entry.target)}})},{rootMargin:'0px 0px -60px 0px',threshold:0.1});els.forEach(function(el){observer.observe(el)})}else{els.forEach(function(el){el.classList.add('animated')})}}
function setupSmoothScroll(){document.addEventListener('click',function(e){var link=e.target.closest('a[href^="#"]');if(!link)return;var href=link.getAttribute('href');if(href==='#')return;var target=document.querySelector(href);if(!target)return;e.preventDefault();var header=document.getElementById('header');var headerHeight=header?header.offsetHeight:70;var quickNav=document.getElementById('quickNav');var qHeight=quickNav?quickNav.offsetHeight:0;var offset=headerHeight+qHeight+16;var targetPos=target.getBoundingClientRect().top+window.pageYOffset-offset;window.scrollTo({top:targetPos,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});if(history.pushState){history.pushState(null,null,href)}
target.setAttribute('tabindex','-1');target.focus({preventScroll:!0})})}
function setupRatingBars(){var bars=document.querySelectorAll('.bar-fill, .mat-fill');if(bars.length===0)return;if('IntersectionObserver' in window){var observer=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){var bar=entry.target;var width=bar.style.width;bar.style.width='0';requestAnimationFrame(function(){requestAnimationFrame(function(){bar.style.width=width})});observer.unobserve(bar)}})},{threshold:0.3});bars.forEach(function(bar){observer.observe(bar)})}}
function setupLazyImages(){var images=document.querySelectorAll('img[loading="lazy"]');images.forEach(function(img){img.style.opacity='0';img.style.transition='opacity 0.4s ease';if(img.complete){img.style.opacity='1'}else{img.addEventListener('load',function(){img.style.opacity='1'});img.addEventListener('error',function(){img.style.opacity='1'})}})}
function setupProgressBar(){var fill=document.querySelector('.progress-fill');if(!fill)return;var ticking=!1;function update(){var scrollTop=window.pageYOffset||document.documentElement.scrollTop;var docHeight=document.documentElement.scrollHeight-window.innerHeight;var progress=docHeight>0?(scrollTop/docHeight)*100:0;fill.style.width=Math.min(progress,100)+'%';var bar=fill.parentElement;if(bar)bar.setAttribute('aria-valuenow',Math.round(progress));ticking=!1}
window.addEventListener('scroll',function(){if(!ticking){requestAnimationFrame(update);ticking=!0}},{passive:!0})}
function setupHeaderScroll(){var header=document.getElementById('header');if(!header)return;var ticking=!1;function update(){header.classList.toggle('scrolled',window.pageYOffset>50);ticking=!1}
window.addEventListener('scroll',function(){if(!ticking){requestAnimationFrame(update);ticking=!0}},{passive:!0})}})()
